# serene v1.2.0 (check for update at https://github.com/isunjn/serene/releases)

base_url = "https://example.com"      # Domain name of your website
title = "sdancer"
description = "hacking stuff"
default_language = "en"
theme = "tranquil"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false            # Keep this false, search is temporarily unsupported
#generate_feed = false         
#feed_filename = "feed.xml"   
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "tranquil-light", filename = "hl-light.css"},
    { theme = "tranquil-dark", filename = "hl-dark.css"},
]
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
insert_anchor_links = "left"
#=========================================================================================

[extra]

name = "Bianchi Federico"                         # Your name
id = "sdancer"                           # Your id / username / handle
bio = "hacking the reality"
avatar = "avatar.jpeg"
links = [                             # Your links
    { name = "GitHub", icon = "github", url = "https://github.com/amadeus-robot" },
    { name = "Twitter", icon = "twitter", url = "https://x.com/realityrefactor" },
    { name = "Email", icon = "email", url = "mailto:ktion23@gmail.com" },
]

nav_separator = " > "

display_id = true                     # Display your id on homepage
projects_page = false # Display projects page
blog_categorized = true               # Whether to categorize blog posts
blur_effect = true                    # Whether to turn on blur effect on navigation bar

toc = true                            # Whether to show Table-Of-Contents by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info
copy = true                           # Whether to add a copy button on code blocks by default
back_to_top = true                    # Whether to show back-to-top button by default

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

call_to_action_footer_text = "Call to action here"
call_to_action_footer = false 

footer_copyright = "© 2025 <Someone>"
footer_credits = true                 # Whether to show "Powered by Zola and Serene" in footer

footer_privacy_text = "Privacy Policy"
footer_privacy = false
